# Generated by Django 4.2.16 on 2024-12-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('chunk_count', models.IntegerField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
