# Generated by Django 4.2.16 on 2024-12-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='last_update',
            field=models.TextField(),
        ),
    ]
