# Generated by Django 4.2.16 on 2024-12-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatsession_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='Empty Session', help_text='Unique identifier for the session', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default='e055696d-d6f5-4f90-8369-e629366342ac', help_text='Unique identifier for the session', max_length=100, unique=True),
        ),
    ]
