# Generated by Django 4.2.16 on 2024-12-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_chatsession_name_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default='5c4fa4dd-9902-4402-902b-11389dece3e1', help_text='Unique identifier for the session', max_length=100, unique=True),
        ),
    ]
