# Generated by Django 4.2.16 on 2024-12-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default='ab96a017-f6c0-4c4e-aebd-a6bad4abb234', help_text='Unique identifier for the session', max_length=100),
        ),
    ]
