# Generated by Django 4.2.16 on 2024-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='name',
            field=models.CharField(default='Empty Session', help_text='Unique name for the session', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default='6e8e97d7-3ebd-4ce7-8740-e8be0eee0c07', help_text='Unique identifier for the session', max_length=100),
        ),
    ]
