# Generated by Django 4.2.16 on 2024-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_alter_chatsession_name_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default='426e6d34-86bf-444f-8353-7157b753f2ba', help_text='Unique identifier for the session', max_length=100, unique=True),
        ),
    ]
